name: Production Deployment

on:
  workflow_dispatch:
  push:
    branches:
      - develop

jobs:
  deployment:
    name: Deploy on remote server
    runs-on: ubuntu-latest

    steps:
      - name: Install SSH keys
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Connect and run commands
        run: |
          ssh -v root@${{ secrets.SSH_HOST }} \
          "cd /var/www/html/crypto-cex-admin \
          && git remote set-url origin git@github.com:${{ secrets.REPOSITORY }}.git \
          && export NVM_DIR=\$HOME/.nvm \
          && source \$NVM_DIR/nvm.sh \
          && git config --global --add safe.directory /var/www/html/crypto-cex-admin \
          && git checkout develop \
          && git pull \
          && npm install \
          && npm run build \
          && exit"

      - name: Cleanup
        run: rm -rf ~/.ssh
